-- ============================================================================
-- TraceX — Supabase schema
-- ============================================================================
-- Run this in the Supabase SQL editor (or `supabase db push`) before seeding.
-- Tables are keyed by domain ids (TXN-…, ACC-…) so re-seeding is idempotent.
-- RLS is enabled everywhere: anon keys can read; authenticated users can read
-- and insert; only the backend (service role / dashboard) mutates freely.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Entities (accounts, wallets, mules, exchanges, shell corps…)
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_entities (
  id                  text primary key,
  node_number         int,
  label               text not null,
  type                text not null,
  risk                text not null check (risk in ('LOW','MEDIUM','HIGH','CRITICAL')),
  risk_score          int not null default 0 check (risk_score between 0 and 100),
  status              text not null default 'NORMAL',
  transaction_count   int not null default 0,
  inflow              bigint not null default 0,
  outflow             bigint not null default 0,
  balance             bigint not null default 0,
  first_seen          timestamptz,
  last_activity       timestamptz,
  cluster_id          text,
  cluster_name        text,
  x                   double precision default 0,
  y                   double precision default 0,
  risk_indicators     jsonb not null default '[]'::jsonb,
  tags                jsonb not null default '[]'::jsonb,
  bank_name           text,
  jurisdiction        text,
  ip_address          text,
  device_fingerprint  text,
  account_holder      text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Transactions (graph edges)
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_transactions (
  id                 text primary key,
  source             text not null references public.tracex_entities(id) on delete cascade,
  target             text not null references public.tracex_entities(id) on delete cascade,
  type               text not null check (type in ('UPI','IMPS','NEFT','RTGS','CARD')),
  amount             bigint not null check (amount >= 0),
  formatted_amount   text,
  timestamp          text,                      -- HH:MM:SS wall clock
  risk               text not null check (risk in ('LOW','MEDIUM','HIGH','CRITICAL')),
  flow_status        text not null default 'SETTLED' check (flow_status in ('SETTLED','IN_TRANSIT','FLAGGED')),
  hash               text,
  note               text,
  suspicious_pattern text,
  created_at         timestamptz not null default now()
);
create index if not exists idx_tracex_tx_source on public.tracex_transactions(source);
create index if not exists idx_tracex_tx_target on public.tracex_transactions(target);
create index if not exists idx_tracex_tx_risk   on public.tracex_transactions(risk);

-- ---------------------------------------------------------------------------
-- Alerts (generated by the pipeline)
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_alerts (
  id             text primary key,
  transaction_id text not null,
  severity       text not null check (severity in ('CRITICAL','HIGH','MEDIUM','LOW')),
  type           text not null,
  message        text not null,
  timestamp      timestamptz not null default now(),
  account_id     text,
  risk_score     int not null default 0,
  status         text not null default 'NEW' check (status in ('NEW','ACKNOWLEDGED','INVESTIGATING','RESOLVED')),
  created_at     timestamptz not null default now()
);
create index if not exists idx_tracex_alerts_tx on public.tracex_alerts(transaction_id);

-- ---------------------------------------------------------------------------
-- Detected suspicious transactions
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_detected_transactions (
  transaction_id   text primary key,
  timestamp        text,
  source           text,
  target           text,
  amount           bigint,
  formatted_amount text,
  type             text,
  risk_level       text check (risk_level in ('LOW','MEDIUM','HIGH','CRITICAL')),
  risk_score       int check (risk_score between 0 and 100),
  signals          jsonb not null default '[]'::jsonb,
  ai_explanation   text,
  trace_path       jsonb not null default '[]'::jsonb,
  scenario_name    text,
  created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Investigation cases
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_cases (
  id                 text primary key,
  title              text not null,
  status             text not null default 'NEW',
  priority           text not null default 'MEDIUM',
  account_id         text,
  risk_score         int default 0,
  risk_level         text,
  confidence_score   int default 0,
  detected_patterns  jsonb not null default '[]'::jsonb,
  evidence           jsonb not null default '[]'::jsonb,
  connected_entities jsonb not null default '[]'::jsonb,
  transaction_paths  jsonb not null default '[]'::jsonb,
  investigator_notes text not null default '',
  analyst            text,
  unit               text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Case activity log
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_case_activity (
  id         text primary key default gen_random_uuid()::text,
  case_id    text not null references public.tracex_cases(id) on delete cascade,
  timestamp  timestamptz not null default now(),
  analyst    text,
  action     text not null,
  tag        text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Raw stream events (live feed persistence)
-- ---------------------------------------------------------------------------
create table if not exists public.tracex_stream_events (
  event_id          text primary key,
  time              text,
  source            text,
  target            text,
  type              text,
  amount            bigint,
  formatted_amount  text,
  risk              text,
  risk_score        int,
  status            text,
  detection_signals jsonb not null default '[]'::jsonb,
  detected          boolean not null default false,
  created_at        timestamptz not null default now()
);
create index if not exists idx_tracex_stream_created on public.tracex_stream_events(created_at);

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.tracex_entities              enable row level security;
alter table public.tracex_transactions          enable row level security;
alter table public.tracex_alerts                enable row level security;
alter table public.tracex_detected_transactions enable row level security;
alter table public.tracex_cases                 enable row level security;
alter table public.tracex_case_activity         enable row level security;
alter table public.tracex_stream_events         enable row level security;

-- Public read for the demo console (publishable key). Tighten for production.
create policy "public read entities"  on public.tracex_entities              for select using (true);
create policy "public read txns"      on public.tracex_transactions          for select using (true);
create policy "public read alerts"    on public.tracex_alerts                for select using (true);
create policy "public read detected"  on public.tracex_detected_transactions for select using (true);
create policy "public read cases"     on public.tracex_cases                 for select using (true);
create policy "public read activity"  on public.tracex_case_activity         for select using (true);
create policy "public read stream"    on public.tracex_stream_events         for select using (true);

-- Authenticated users may insert alerts/detections/cases via the backend path.
create policy "auth insert alerts"   on public.tracex_alerts    for insert to authenticated with check (true);
create policy "auth insert detected" on public.tracex_detected_transactions for insert to authenticated with check (true);
create policy "auth insert cases"    on public.tracex_cases     for insert to authenticated with check (true);
create policy "auth update cases"    on public.tracex_cases     for update to authenticated using (true);
